#!/usr/bin/env node

/**
 * si-vertical-spawn.ts
 *
 * Scaffolds a new 'House' (e.g., House of Space) acting as an autonomous harness.
 * Absorbs the ruvnet/metaharness pattern:
 * - Dynamically provisions an isolated SQLite/vector namespace
 * - Creates necessary domain sub-directories under src/<domain>
 * - Generates a Git-backed CLI entrypoint script for that specific House
 */

import { parseArgs } from "node:util";
import { existsSync, mkdirSync, writeFileSync, chmodSync } from "node:fs";
import { join } from "node:path";

export function spawnHouse(houseName: string, domainArg?: string): void {
  const domainName = domainArg ?? houseName.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  const rootDir = process.cwd();
  
  // 1. Create domain sub-directories under src/<domain>
  const domainPath = join(rootDir, "src", domainName);
  if (existsSync(domainPath)) {
    console.warn(`[si-vertical-spawn] Domain path already exists: ${domainPath}`);
  } else {
    mkdirSync(domainPath, { recursive: true });
    mkdirSync(join(domainPath, "memory"), { recursive: true });
    mkdirSync(join(domainPath, "skills"), { recursive: true });
    console.log(`[si-vertical-spawn] Created domain directory: ${domainPath}`);
  }

  // 2. Dynamically provision an isolated SQLite/vector namespace
  const dbNamespacePath = join(rootDir, "memory", "vaults", domainName);
  if (!existsSync(dbNamespacePath)) {
    mkdirSync(dbNamespacePath, { recursive: true });
    writeFileSync(
      join(dbNamespacePath, "namespace.json"),
      JSON.stringify({ house: houseName, domain: domainName, type: "isolated-sqlite-vector-namespace", created: new Date().toISOString() }, null, 2),
      "utf-8"
    );
    console.log(`[si-vertical-spawn] Provisioned isolated namespace at: ${dbNamespacePath}`);
  }

  // 3. Generate a Git-backed CLI entrypoint script for that specific House
  const binDir = join(rootDir, "bin");
  if (!existsSync(binDir)) {
    mkdirSync(binDir, { recursive: true });
  }

  const cliScriptName = `si-${domainName}.ts`;
  const cliScriptPath = join(binDir, cliScriptName);
  
  const cliScriptContent = `#!/usr/bin/env node

/**
 * Autonomous harness for ${houseName}
 * Generated by si-vertical-spawn
 */

import { parseArgs } from "node:util";
import { join } from "node:path";

function run() {
  const { values, positionals } = parseArgs({
    args: process.argv.slice(2),
    options: {
      help: { type: "boolean" }
    },
    allowPositionals: true
  });

  if (values.help) {
    console.log("Usage: ${cliScriptName} [options]");
    process.exit(0);
  }

  console.log("Welcome to ${houseName} Autonomous Harness");
  console.log("Domain:", "${domainName}");
  console.log("Isolated Namespace:", join(process.cwd(), "memory", "vaults", "${domainName}"));
}

run();
`;

  if (!existsSync(cliScriptPath)) {
    writeFileSync(cliScriptPath, cliScriptContent, "utf-8");
    try {
      chmodSync(cliScriptPath, 0o755);
    } catch (err) {
      // ignore on windows
    }
    console.log(`[si-vertical-spawn] Generated CLI entrypoint: ${cliScriptPath}`);
  } else {
    console.warn(`[si-vertical-spawn] CLI entrypoint already exists: ${cliScriptPath}`);
  }
  
  // Also create a basic index.ts for the domain
  const indexTsPath = join(domainPath, "index.ts");
  if (!existsSync(indexTsPath)) {
    writeFileSync(
      indexTsPath,
      `export const HouseInfo = {\n  name: "${houseName}",\n  domain: "${domainName}"\n};\n`,
      "utf-8"
    );
    console.log(`[si-vertical-spawn] Created domain index: ${indexTsPath}`);
  }

  console.log(`[si-vertical-spawn] Scaffolded ${houseName} successfully.`);
}

export function main(): void {
  const { values, positionals } = parseArgs({
    args: process.argv.slice(2),
    options: {
      help: { type: "boolean", short: "h" },
      domain: { type: "string", short: "d" },
    },
    allowPositionals: true,
  });

  if (values.help || positionals.length === 0) {
    console.log(`
Usage: si-vertical-spawn <HouseName> [options]

Options:
  --domain, -d    Specific domain directory name (defaults to lowercase HouseName)
  --help, -h      Show help
`);
    process.exit(0);
  }

  const houseName = positionals[0];
  spawnHouse(houseName, values.domain);
}

// Auto-execute if run directly
if (
  process.argv[1] &&
  (process.argv[1].endsWith('si-vertical-spawn.ts') || process.argv[1].endsWith('si-vertical-spawn.js'))
) {
  main();
}
