
const $=id=>document.getElementById(id), make=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const money=x=>new Intl.NumberFormat(navigator.language,{style:"currency",currency:"USD"}).format(x/100);
let draft=cloneJSON(INITIAL),selected="source",impacted=new Set(),undo=null,keys={},dirty=false,epoch=0,editSerial=0,context=null,pan=null;
let view={x:20,y:20,z:.67};
const small=()=>matchMedia("(max-width:700px)").matches,storeKey="starlight.creative-lab.v1."+CONFIG.brand;
const announce=(s,error=false)=>{$("status").textContent=s;$("status").style.color=error?"var(--danger)":"var(--muted)";};
const preview=n=>n.data.text||n.data.draft||n.data.rule||n.data.lighting||n.data.rubric||(n.data.provider?n.data.provider+" · "+n.data.model+" · request draft":n.data.snapshot)||Object.entries(n.data).map(([k,v])=>k+": "+String(v)).join(" · ");
function svgIcon(){const s=document.createElementNS("http://www.w3.org/2000/svg","svg"),p=document.createElementNS(s.namespaceURI,"path");s.setAttribute("viewBox","0 0 18 18");s.setAttribute("aria-hidden","true");p.setAttribute("d","M3 3h12v12H3z M6 6h6M6 9h6M6 12h3");s.append(p);return s;}
function paint(){$("plane").style.transform="translate("+view.x+"px,"+view.y+"px) scale("+view.z+")";$("zoom-value").textContent=small()?"List":new Intl.NumberFormat(navigator.language,{style:"percent",maximumFractionDigits:0}).format(view.z);}
function zoom(delta){if(small())return;const c=$("canvas"),old=view.z;view.z=Math.max(.18,Math.min(1.6,old+delta));view.x=c.clientWidth/2-(c.clientWidth/2-view.x)*view.z/old;view.y=c.clientHeight/2-(c.clientHeight/2-view.y)*view.z/old;paint();}
function fit(){if(small())return;const w=Math.max(...draft.nodes.map(n=>n.position.x+240)),h=Math.max(...draft.nodes.map(n=>n.position.y+174));view={x:20,y:20,z:Math.max(.18,Math.min(1,($("canvas").clientWidth-40)/w,($("canvas").clientHeight-40)/h))};paint();}
function choose(id,centre=false){const n=draft.nodes.find(n=>n.id===id);if(!n)return;selected=id;$("node-title").textContent=n.label||id;$("node-detail").textContent=NODE_TYPES[n.type].paid?"Media request draft. This lab does not call the provider.":CONFIG.details[n.type]||"Inspect and edit this draft step.";$("node-data").value=JSON.stringify(n.data,null,2);$("node-error").textContent="";$("ports").replaceChildren();draft.edges.filter(e=>e.from===id||e.to===id).forEach(e=>$("ports").append(make("p",e.from+"."+e.output+" → "+e.to+"."+e.input)));$("key-label").textContent=keys[id]||"Calculating semantic identity…";document.querySelectorAll(".node-card").forEach(c=>c.classList.toggle("selected",c.dataset.id===id));$("jump-node").value=id;const u=new URL(location.href);u.searchParams.set("node",id);history.replaceState(null,"",u);if(centre&&!small()){view.x=$("canvas").clientWidth/2-(n.position.x+120)*view.z;view.y=100-n.position.y*view.z;paint();}}
function plan(w=draft){const raw=$("planning-cap").value,a=Number(raw),minor=Math.round(a*100);if(!raw.trim()||!Number.isFinite(a)||a<0||a>1000||Math.abs(a*100-minor)>.000001)throw new Error("Enter a cap from 0 to 1000 USD with at most two decimal places.");return compileWorkflow(w,{workflowRevision:w.revision,worldRevision:w.worldRevision,maxCostMinor:minor,currency:w.currency,allowedProviders:["xai","gemini","higgsfield"]});}
function selectContext(){try{context=compileContext(CONTEXT_RECORDS,{tenantId:INITIAL.tenantId,worldId:INITIAL.worldId,worldRevision:INITIAL.worldRevision,namespaces:["Creative"],visibility:["private"],tokenBudget:Number($("context-budget").value),requiredIds:CONFIG.requiredIds,queryTerms:CONFIG.queryTerms});$("context-list").replaceChildren();context.records.forEach(r=>{const row=make("div",undefined,"context-record");row.append(make("strong",r.title||r.id),make("p",r.text),make("p",CONFIG.requiredIds.includes(r.id)?"Required example context":"Optional example context"));$("context-list").append(row);});$("context-summary").textContent=context.records.length+" selected · "+context.excludedCount+" excluded · "+context.tokens+" estimated units";$("proof-context").textContent=context.records.length+" example records";return context;}catch(e){context=null;$("context-list").replaceChildren();$("context-summary").textContent=e.message;$("proof-context").textContent="Selection blocked";throw e;}}
function edges(){$("edges").replaceChildren();draft.edges.forEach(e=>{const a=draft.nodes.find(n=>n.id===e.from),b=draft.nodes.find(n=>n.id===e.to),p=document.createElementNS("http://www.w3.org/2000/svg","path"),x=a.position.x+240,y=a.position.y+88,xx=b.position.x,yy=b.position.y+88,c=Math.max(55,Math.abs(xx-x)/2);p.setAttribute("d","M "+x+" "+y+" C "+(x+c)+" "+y+", "+(xx-c)+" "+yy+", "+xx+" "+yy);p.setAttribute("class","edge"+(impacted.has(e.to)?" affected":""));$("edges").append(p);});}
function remember(){undo=cloneJSON(draft);$("undo").disabled=false;}
async function render(){
 $("nodes").replaceChildren();$("jump-node").replaceChildren();
 for(const id of validateWorkflow(draft).order){
  const n=draft.nodes.find(n=>n.id===id),c=make("div",undefined,"node-card"+(impacted.has(id)?" affected":""));c.dataset.id=id;c.style.transform="translate("+n.position.x+"px,"+n.position.y+"px)";
  const b=make("button",undefined,"node-select"),kind=make("span",undefined,"node-kind");b.type="button";b.setAttribute("aria-label","Inspect "+(n.label||id));kind.append(svgIcon(),make("span",CONFIG.kindLabels[n.type]||n.type));b.append(kind,make("span",n.label||id,"node-heading"),make("span",preview(n),"node-preview"));b.addEventListener("click",()=>choose(id));c.append(b);
  const bottom=make("div",undefined,"node-bottom"),move=make("button",undefined,"drag-handle");bottom.append(make("span",impacted.has(id)?"Needs another pass":NODE_TYPES[n.type].paid?"Request draft":"Draft","node-state"));move.type="button";move.setAttribute("aria-label","Move "+(n.label||id)+". Use arrow keys.");move.append(svgIcon());let dragging=null;
  move.addEventListener("pointerdown",e=>{if(small())return;e.stopPropagation();remember();dragging={x:e.clientX,y:e.clientY,nx:n.position.x,ny:n.position.y};move.setPointerCapture(e.pointerId);});
  move.addEventListener("pointermove",e=>{if(!dragging)return;n.position={x:Math.min(10000,Math.max(0,Math.round(dragging.nx+(e.clientX-dragging.x)/view.z))),y:Math.min(10000,Math.max(0,Math.round(dragging.ny+(e.clientY-dragging.y)/view.z)))};c.style.transform="translate("+n.position.x+"px,"+n.position.y+"px)";edges();dirty=true;editSerial++;});
  ["pointerup","pointercancel"].forEach(t=>move.addEventListener(t,()=>{if(dragging)announce("Layout changed. Semantic keys are preserved.");dragging=null;}));
  move.addEventListener("keydown",e=>{const d={ArrowLeft:[-20,0],ArrowRight:[20,0],ArrowUp:[0,-20],ArrowDown:[0,20]}[e.key];if(!d)return;e.preventDefault();remember();n.position={x:Math.min(10000,Math.max(0,n.position.x+d[0])),y:Math.min(10000,Math.max(0,n.position.y+d[1]))};c.style.transform="translate("+n.position.x+"px,"+n.position.y+"px)";edges();dirty=true;editSerial++;announce("Node moved. Semantic keys are preserved.");});
  bottom.append(move);c.append(bottom);$("nodes").append(c);const o=make("option",n.label||id);o.value=id;$("jump-node").append(o);
 }
 edges();$("intent").value=draft.nodes.find(n=>n.id==="source").data.text;$("work-title").textContent=draft.title;$("revision-label").textContent="Draft revision "+draft.revision+" · example context "+draft.worldRevision;$("proof-revision").textContent=draft.revision+" / "+draft.worldRevision;$("graph-caption").textContent=draft.nodes.length+" steps · "+draft.edges.length+" links";$("impact-label").textContent=impacted.size?impacted.size+" steps need another pass.":"Select a node to inspect it.";
 try{const p=plan();$("proof-graph").textContent="Valid draft";$("cost-label").textContent=money(p.estimatedMinor)+" synthetic estimate";}catch(e){$("proof-graph").textContent="Needs correction";$("cost-label").textContent=e.message;}
 choose(selected);paint();const ticket=epoch,result=await nodeKeys(draft);if(ticket===epoch){keys=result;$("key-label").textContent=keys[selected]||"";}
}
function change(next,ids,message){remember();draft=next;impacted=new Set(ids);dirty=true;epoch++;editSerial++;render();announce(message);}
$("save-node").addEventListener("click",()=>{try{const p=applyDraftPatch(draft,{baseRevision:draft.revision,worldRevision:draft.worldRevision,operations:[{kind:"replace-data",nodeId:selected,data:(()=>{const d=JSON.parse($("node-data").value);if(CONFIG.brand==="gencreator"&&["article","social","script"].includes(selected)&&d&&typeof d==="object"&&!Array.isArray(d))d.editorOrigin="creator";return d;})()}]});change(p.workflow,p.affected,"Node edit saved. "+p.affected.length+" dependent steps need another pass.");}catch(e){$("node-error").textContent=e.message;$("node-data").focus();announce("Correct the node settings before saving.",true);}});
$("apply-source").addEventListener("click",()=>{try{const text=$("intent").value,ops=[{kind:"replace-data",nodeId:"source",data:{...draft.nodes.find(n=>n.id==="source").data,text}}];if(CONFIG.brand==="gencreator"){const excerpt=text.trim().slice(0,1200),headline=text.trim().split(/[.!?\n]/)[0].slice(0,85);for(const id of ["article","social","script"])ops.push({kind:"replace-data",nodeId:id,data:draft.nodes.find(n=>n.id===id).data.editorOrigin==="creator"?{...draft.nodes.find(n=>n.id===id).data,sourceReviewRequired:true}:{...draft.nodes.find(n=>n.id===id).data,draft:"Working "+id+": "+headline+"\n\nSource excerpt:\n"+excerpt+"\n\nAdd your concrete example, permitted visuals and a source-backed conclusion before use."}});}const p=applyDraftPatch(draft,{baseRevision:draft.revision,worldRevision:draft.worldRevision,operations:ops});selected="source";change(p.workflow,p.affected,CONFIG.brand==="gencreator"?"Source updated. Creator edits are preserved; affected formats need review.":"Brief updated. Inspect the highlighted dependencies.");}catch(e){announce(e.message,true);$("intent").focus();}});
$("validate").addEventListener("click",()=>{try{const p=plan();$("proof-graph").textContent="Valid draft";announce("Graph valid at revision "+draft.revision+". "+p.waves.length+" dependency waves · "+money(p.estimatedMinor)+" synthetic estimate.");}catch(e){$("proof-graph").textContent="Needs correction";announce(e.message,true);$("planning-cap").focus();}});
["planning-cap","context-budget"].forEach(id=>$(id).addEventListener("input",()=>{dirty=true;editSerial++;}));
$("compile-context").addEventListener("click",()=>{try{selectContext();announce("Context inspected. Required example records remain in the packet.");}catch(e){announce(e.message,true);$("context-budget").focus();}});
$("save").addEventListener("click",()=>{try{localStorage.setItem(storeKey,JSON.stringify({workflow:draft,selected,impacted:[...impacted],planningCap:$("planning-cap").value,contextBudget:$("context-budget").value}));dirty=false;announce("Draft saved in this browser. No account write occurred.");}catch{announce("Local save failed. Export the draft to keep a copy.",true);}});
$("restore").addEventListener("click",()=>{try{const raw=localStorage.getItem(storeKey);if(!raw){announce("No local draft is saved yet.");return;}if(raw.length>262144)throw new Error("Saved draft exceeds this lab's limit.");const s=JSON.parse(raw);validateWorkflow(s.workflow);if(s.workflow.nodes.some(n=>!n.position||!Number.isSafeInteger(n.position.x)||!Number.isSafeInteger(n.position.y)||n.position.x<0||n.position.y<0||n.position.x>10000||n.position.y>10000)||INITIAL.nodes.some(n=>!s.workflow.nodes.some(x=>x.id===n.id&&x.type===n.type)))throw new Error("Saved draft has an invalid canvas shape or belongs to an older lab.");if(s.workflow.nodes.length>40||s.workflow.tenantId!==INITIAL.tenantId||s.workflow.worldId!==INITIAL.worldId||s.workflow.worldRevision!==INITIAL.worldRevision)throw new Error("Saved draft belongs to another example or exceeds this lab's limit.");for(const field of ["planningCap","contextBudget"]){if(s[field]!==undefined&&(typeof s[field]!=="string"||s[field].length>24||!s[field].trim()||!Number.isFinite(Number(s[field]))))throw new Error("Saved draft has invalid planning settings.");}if(s.impacted!==undefined&&(!Array.isArray(s.impacted)||s.impacted.length>40||s.impacted.some(id=>!s.workflow.nodes.some(n=>n.id===id))))throw new Error("Saved draft has invalid dependency state.");if(s.planningCap!==undefined)$("planning-cap").value=s.planningCap;if(s.contextBudget!==undefined)$("context-budget").value=s.contextBudget;selected=s.workflow.nodes.some(n=>n.id===s.selected)?s.selected:"source";change(cloneJSON(s.workflow),s.impacted||[],"Saved draft restored. Inspect it before export.");dirty=false;try{selectContext();}catch(e){announce(e.message,true);}}catch(e){announce(e.message,true);}});
$("add-step").addEventListener("click",()=>{try{if(draft.nodes.length>=40)throw new Error("This lab supports 40 steps.");const w=cloneJSON(draft),id="text-step-"+(w.revision+1)+"-"+w.nodes.length;w.nodes.push({id,type:"transform",label:"New text step",position:{x:350,y:Math.max(...w.nodes.map(n=>n.position.y))+205},data:{format:"notes",draft:"Add a grounded draft or production note."}});w.edges.push({id:"source-"+id,from:"source",output:"text",to:id,input:"text"});w.revision++;validateWorkflow(w);selected=id;change(w,[id],"Text step added and ready to edit.");choose(id,true);}catch(e){announce(e.message,true);}});
$("undo").addEventListener("click",()=>{if(!undo)return;const w=undo;undo=null;draft=w;selected=w.nodes.some(n=>n.id===selected)?selected:"source";impacted=new Set();dirty=true;epoch++;editSerial++;$("undo").disabled=true;render();announce("Last edit undone. Previous draft revision restored.");});
async function exportManifest(){const w=cloneJSON(draft),p=plan(w),c=selectContext();return {schema:"starlight.creative-export.v1",kind:"local-draft",product:CONFIG.brand,identityVerified:false,authorization:null,publishAuthorization:null,canonChanged:false,workflow:w,context:c,plan:p,semanticKeys:await nodeKeys(w),workflowDigest:await sha256(w),kernel:{version:VERSION,digest:CONFIG.kernelDigest,repository:CONFIG.sourceRepository,ref:CONFIG.sourceRef},exportedAt:new Date().toISOString()};}
function download(name,data,type){const url=URL.createObjectURL(new Blob([data],{type})),a=make("a");a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$("export").addEventListener("click",async()=>{const exportedEdit=editSerial;$("export").disabled=true;try{const m=await exportManifest();download(CONFIG.brand+"-creative-draft-r"+m.workflow.revision+".json",JSON.stringify(m,null,2)+"\n","application/json");if(editSerial===exportedEdit)dirty=false;announce(editSerial===exportedEdit?"Draft exported with context, semantic keys and explicit unverified authorization.":"Exported revision "+m.workflow.revision+". Your newer changes still need saving or export.");}catch(e){announce("Export needs correction: "+e.message,true);}finally{$("export").disabled=false;}});
$("export-markdown").addEventListener("click",async()=>{const exportedEdit=editSerial;try{const m=await exportManifest(),lines=["# "+m.workflow.title,"","Local draft · "+CONFIG.name,"","## Work"];m.plan.order.forEach(id=>{const n=m.workflow.nodes.find(n=>n.id===id);lines.push("","### "+(n.label||id),preview(n));});lines.push("","## Context",...m.context.records.map(r=>"- "+(r.title||r.id)+": "+r.text),"","## Handoff","Media execution, server identity, rights and exact approval need the connected product.","","Workflow digest: "+m.workflowDigest);download(CONFIG.brand+"-creative-plan.md",lines.join("\n"),"text/markdown");if(editSerial===exportedEdit)dirty=false;announce(editSerial===exportedEdit?"Readable plan exported.":"Readable plan exported at revision "+m.workflow.revision+". Your newer changes still need saving or export.");}catch(e){announce("Export needs correction: "+e.message,true);}});
$("zoom-in").addEventListener("click",()=>zoom(.1));$("zoom-out").addEventListener("click",()=>zoom(-.1));$("fit").addEventListener("click",fit);$("center").addEventListener("click",()=>choose(selected,true));$("jump-node").addEventListener("change",e=>choose(e.target.value,true));
$("canvas").addEventListener("pointerdown",e=>{if(small()||e.target.closest(".node-card"))return;pan={x:e.clientX,y:e.clientY,vx:view.x,vy:view.y};$("canvas").setPointerCapture(e.pointerId);});$("canvas").addEventListener("pointermove",e=>{if(pan){view.x=pan.vx+e.clientX-pan.x;view.y=pan.vy+e.clientY-pan.y;paint();}});["pointerup","pointercancel"].forEach(t=>$("canvas").addEventListener(t,()=>pan=null));
$("canvas").addEventListener("wheel",e=>{if(small()||e.ctrlKey)return;e.preventDefault();zoom(e.deltaY>0?-.05:.05);},{passive:false});
$("canvas").addEventListener("keydown",e=>{if(e.target!==$("canvas")||small())return;const d={ArrowLeft:[40,0],ArrowRight:[-40,0],ArrowUp:[0,40],ArrowDown:[0,-40]}[e.key];if(d){e.preventDefault();view.x+=d[0];view.y+=d[1];paint();}else if(["+","=","-","Home"].includes(e.key)){e.preventDefault();e.key==="Home"?fit():zoom(e.key==="-"?-.1:.1);}});
document.querySelectorAll("[data-pane]").forEach(b=>b.addEventListener("click",()=>{const p=b.dataset.pane;document.querySelectorAll("[data-pane]").forEach(n=>n.setAttribute("aria-pressed",String(n===b)));["source","context","team"].forEach(id=>$(id+"-pane").hidden=id!==p);const u=new URL(location.href);u.searchParams.set("panel",p);history.replaceState(null,"",u);}));
TEAM.roles.filter(r=>!r.id.startsWith("arcanea-")&&!r.id.startsWith("gencreator-")||r.id.startsWith(CONFIG.brand+"-")).slice(0,5).forEach(r=>{const row=make("div",undefined,"team-record");row.append(make("strong",r.id.replaceAll("-"," ")),make("p",r.task),make("p","Quality: "+r.eval));$("team-list").append(row);});
$("intent-label").textContent=CONFIG.brand==="gencreator"?"Your permitted source":"Your scene brief";
const initialURL=new URL(location.href);if(draft.nodes.some(n=>n.id===initialURL.searchParams.get("node")))selected=initialURL.searchParams.get("node");const pane=initialURL.searchParams.get("panel");if(["context","team"].includes(pane))document.querySelector('[data-pane="'+pane+'"]').click();
try{selectContext();}catch(e){announce(e.message,true);}await render();announce(CONFIG.initialMessage);
window.addEventListener("resize",paint);window.addEventListener("beforeunload",e=>{if(dirty){e.preventDefault();e.returnValue="";}});

