/**
 * The Forge (Automated Test Synthesizer)
 * 
 * Takes empirically validated patterns from the Technical Vault
 * and synthesizes permanent, executable regression tests.
 */

import { writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { VaultMemory } from "./vault-memory.js";
import { EmpiricalSandbox, type SupportedLanguage } from "./sandbox.js";

export class TestForge {
  constructor(private memory: VaultMemory) {}

  /**
   * Scan the Technical Vault for high-confidence, verified patterns
   * and synthesize them into test files.
   */
  public async forgeTests(): Promise<string[]> {
    const forgedFiles: string[] = [];
    
    // 1. Get verified patterns
    const patterns = this.memory.searchVaults({
      query: "pattern",
      vaults: ["technical"],
      minConfidence: 0.8
    });

    const verified = patterns.filter(p => !p.entry.tags.includes("unverified-pattern"));

    if (verified.length === 0) return [];

    // 2. Synthesize each pattern into a test file
    for (const pattern of verified) {
      const codeBlocks = EmpiricalSandbox.extractCodeBlocks(pattern.entry.content);
      if (codeBlocks.length === 0) continue;

      const fileName = `forge_${pattern.entry.id.replace(/[^a-zA-Z0-9]/g, "_")}.test.ts`;
      const filePath = join(process.cwd(), "test", "forged", fileName);

      // Ensure directory exists
      const dir = join(process.cwd(), "test", "forged");
      if (!existsSync(dir)) {
        mkdirSync(dir, { recursive: true });
      }

      const testContent = this.generateTestContent(pattern.entry.id, codeBlocks);
      writeFileSync(filePath, testContent, "utf-8");
      forgedFiles.push(filePath);
    }

    return forgedFiles;
  }

  /**
   * Generate the TypeScript test file content.
   */
  private generateTestContent(id: string, blocks: { language: SupportedLanguage, code: string }[]): string {
    return `/**
 * Forged Regression Test: ${id}
 * Generated by Starlight Test Forge
 */

import { test } from "node:test";
import assert from "node:assert";
import { EmpiricalSandbox } from "../../src/sandbox.js";

test("Forged Pattern Validation: ${id}", async () => {
  ${blocks.map((block, i) => `
  // Validating block ${i} (${block.language})
  const result${i} = EmpiricalSandbox.validatePattern(\`${block.code.replace(/`/g, "\\`").replace(/\${/g, "\\${")}\`, "${block.language}");
  assert.strictEqual(result${i}.success, true, \`Pattern block ${i} failed execution: \${result${i}.output}\`);
  `).join("\n")}
});
`;
  }
}
